export type MlbTeamRating = {
  offenseVsRhp: number;
  offenseVsLhp: number;
  bullpen: number;
  startingPitching: number;
};

export const mlbTeamRatings: Record<string, MlbTeamRating> = {
  "Arizona Diamondbacks": { offenseVsRhp: 104, offenseVsLhp: 102, bullpen: 101, startingPitching: 101 },
  "Atlanta Braves": { offenseVsRhp: 108, offenseVsLhp: 110, bullpen: 103, startingPitching: 104 },
  "Athletics": { offenseVsRhp: 95, offenseVsLhp: 94, bullpen: 95, startingPitching: 94 },
  "Baltimore Orioles": { offenseVsRhp: 107, offenseVsLhp: 106, bullpen: 103, startingPitching: 102 },
  "Boston Red Sox": { offenseVsRhp: 101, offenseVsLhp: 99, bullpen: 97, startingPitching: 98 },
  "Chicago Cubs": { offenseVsRhp: 104, offenseVsLhp: 101, bullpen: 102, startingPitching: 103 },
  "Chicago White Sox": { offenseVsRhp: 91, offenseVsLhp: 90, bullpen: 92, startingPitching: 92 },
  "Cincinnati Reds": { offenseVsRhp: 98, offenseVsLhp: 97, bullpen: 96, startingPitching: 97 },
  "Cleveland Guardians": { offenseVsRhp: 102, offenseVsLhp: 101, bullpen: 104, startingPitching: 101 },
  "Colorado Rockies": { offenseVsRhp: 93, offenseVsLhp: 95, bullpen: 90, startingPitching: 90 },
  "Detroit Tigers": { offenseVsRhp: 99, offenseVsLhp: 98, bullpen: 101, startingPitching: 102 },
  "Houston Astros": { offenseVsRhp: 105, offenseVsLhp: 106, bullpen: 102, startingPitching: 103 },
  "Kansas City Royals": { offenseVsRhp: 101, offenseVsLhp: 100, bullpen: 99, startingPitching: 100 },
  "Los Angeles Angels": { offenseVsRhp: 95, offenseVsLhp: 96, bullpen: 94, startingPitching: 95 },
  "Los Angeles Dodgers": { offenseVsRhp: 112, offenseVsLhp: 109, bullpen: 105, startingPitching: 106 },
  "Miami Marlins": { offenseVsRhp: 92, offenseVsLhp: 91, bullpen: 94, startingPitching: 95 },
  "Milwaukee Brewers": { offenseVsRhp: 103, offenseVsLhp: 102, bullpen: 104, startingPitching: 102 },
  "Minnesota Twins": { offenseVsRhp: 101, offenseVsLhp: 103, bullpen: 101, startingPitching: 101 },
  "New York Mets": { offenseVsRhp: 102, offenseVsLhp: 101, bullpen: 99, startingPitching: 99 },
  "New York Yankees": { offenseVsRhp: 110, offenseVsLhp: 107, bullpen: 104, startingPitching: 105 },
  "Oakland Athletics": { offenseVsRhp: 95, offenseVsLhp: 94, bullpen: 95, startingPitching: 94 },
  "Philadelphia Phillies": { offenseVsRhp: 108, offenseVsLhp: 104, bullpen: 103, startingPitching: 104 },
  "Pittsburgh Pirates": { offenseVsRhp: 96, offenseVsLhp: 95, bullpen: 98, startingPitching: 98 },
  "San Diego Padres": { offenseVsRhp: 106, offenseVsLhp: 104, bullpen: 103, startingPitching: 103 },
  "San Francisco Giants": { offenseVsRhp: 98, offenseVsLhp: 100, bullpen: 101, startingPitching: 101 },
  "Seattle Mariners": { offenseVsRhp: 100, offenseVsLhp: 99, bullpen: 103, startingPitching: 105 },
  "St. Louis Cardinals": { offenseVsRhp: 99, offenseVsLhp: 103, bullpen: 98, startingPitching: 99 },
  "Tampa Bay Rays": { offenseVsRhp: 99, offenseVsLhp: 101, bullpen: 102, startingPitching: 101 },
  "Texas Rangers": { offenseVsRhp: 103, offenseVsLhp: 104, bullpen: 98, startingPitching: 100 },
  "Toronto Blue Jays": { offenseVsRhp: 101, offenseVsLhp: 100, bullpen: 101, startingPitching: 100 },
  "Washington Nationals": { offenseVsRhp: 94, offenseVsLhp: 93, bullpen: 95, startingPitching: 94 },
};

export const mlbParkFactors: Record<string, number> = {
  "Arizona Diamondbacks": 1.01,
  "Atlanta Braves": 1.02,
  "Athletics": 0.95,
  "Baltimore Orioles": 0.99,
  "Boston Red Sox": 1.04,
  "Chicago Cubs": 1.02,
  "Chicago White Sox": 1.01,
  "Cincinnati Reds": 1.05,
  "Cleveland Guardians": 0.98,
  "Colorado Rockies": 1.16,
  "Detroit Tigers": 0.97,
  "Houston Astros": 0.99,
  "Kansas City Royals": 0.99,
  "Los Angeles Angels": 1.01,
  "Los Angeles Dodgers": 0.98,
  "Miami Marlins": 0.94,
  "Milwaukee Brewers": 1.01,
  "Minnesota Twins": 1.00,
  "New York Mets": 0.97,
  "New York Yankees": 1.01,
  "Oakland Athletics": 0.95,
  "Philadelphia Phillies": 1.02,
  "Pittsburgh Pirates": 0.98,
  "San Diego Padres": 0.96,
  "San Francisco Giants": 0.95,
  "Seattle Mariners": 0.97,
  "St. Louis Cardinals": 0.98,
  "Tampa Bay Rays": 0.97,
  "Texas Rangers": 1.04,
  "Toronto Blue Jays": 1.01,
  "Washington Nationals": 1.00,
};
