export type PickRecord = {
  id?: number;
  pick_date: string;
  sport: "NBA" | "NFL" | "MLB";
  market_scope: "team" | "player_prop" | "live";
  market_type: string;
  game_label: string;
  home_team?: string | null;
  away_team?: string | null;
  player_name?: string | null;
  sportsbook?: string;
  side: string;
  line_taken?: number | null;
  odds_taken: number;
  stake_units: number;
  confidence_score?: number | null;
  projected_line?: number | null;
  market_line?: number | null;
  edge?: number | null;
  edge_label?: string | null;
  top_pick_rank?: number | null;
  is_top_pick?: boolean;
  status?: "pending" | "win" | "loss" | "push";
  final_score?: string | null;
  final_stat?: number | null;
  closing_line?: number | null;
  clv?: number | null;
  notes?: string | null;
};